USE [master]
GO

/****** Object:  Database [RecApp]    Script Date: 9/11/2016 9:45:40 AM ******/
CREATE DATABASE [RecApp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'aspnet-MvcPWy-20140807072429.mdf', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\aspnet-MvcPWy-20140807072429.mdf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'aspnet-MvcPWy-20140807072429_log.ldf', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\aspnet-MvcPWy-20140807072429_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [RecApp] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RecApp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RecApp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RecApp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RecApp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RecApp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RecApp] SET ARITHABORT OFF 
GO

ALTER DATABASE [RecApp] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [RecApp] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [RecApp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RecApp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RecApp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RecApp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RecApp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RecApp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RecApp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RecApp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RecApp] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RecApp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RecApp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RecApp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RecApp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RecApp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RecApp] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [RecApp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RecApp] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [RecApp] SET  MULTI_USER 
GO

ALTER DATABASE [RecApp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RecApp] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RecApp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RecApp] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [RecApp] SET  READ_WRITE 
GO

